// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

// @ts-ignore: Prisma config tipleri için TypeScript'i susturuyoruz
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // @ts-ignore: Node process tipleri için TypeScript'i susturuyoruz
    url: process.env["DATABASE_URL"],
  },
});